
// -- Anonymous account
INSERT INTO customers (ID, EMAIL) VALUES (1, 'anonymous@homebeauty.com');

-- Service HAIR / MEN
INSERT INTO services (ID, NAME,SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (1, 'Shampoing','HAIR','MEN', 10);
INSERT INTO services (ID, NAME,SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (2, 'Coupe','HAIR','MEN', 10);
INSERT INTO services (ID, NAME,SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (3, 'Couleur','HAIR','MEN', 10);
INSERT INTO services (ID, NAME,SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (4, 'Taille de la barbe','HAIR','MEN', 10);
INSERT INTO services (ID, NAME,SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (5, 'Rasage','HAIR','MEN', 10);

-- Service HAIR / CHILD
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (6, 'Coupe','HAIR','CHILD', 10);

-- Service HAIR / WOMEN
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (7, 'Shampoing ','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (8, 'Soin profond ','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (9, 'Coupe classique','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (10, 'Coupe création','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (11, 'Brushing','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (12, 'Couleur','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (13, 'Tie and dye','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (14, 'Mèches','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (15, 'Balayage','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (16, 'Patine','HAIR','WOMEN', 10);
INSERT INTO services (ID, NAME, SERVICE_TYPE, CUSTOMER_TYPE, PRICE) VALUES (17, 'Coiffure de mariée','HAIR','WOMEN', 10);
