INSERT INTO customers (ID, EMAIL, PASSWORD, PHONE_NUMBER, FIRST_NAME, LAST_NAME) VALUES (1, 'abdo@gmail.com','abdo', '06123456789', 'abdo','khdime');
INSERT INTO customers (ID, EMAIL, PASSWORD, PHONE_NUMBER, FIRST_NAME, LAST_NAME) VALUES (2, 'monsif@gmail.com','monsif', '06123456789', 'Monsif','EL AISSOUSSI');


INSERT INTO estheticians (ID, EMAIL, PASSWORD, PHONE_NUMBER, FIRST_NAME, LAST_NAME) VALUES (1, 'est1@gmail.com', 'est1', '06123456789', 'est2Fname','est2Fname');
INSERT INTO estheticians (ID, EMAIL, PASSWORD, PHONE_NUMBER, FIRST_NAME, LAST_NAME) VALUES (2, 'est2@gmail.com', 'est2', '06123456789', 'est1Fname','est2LName');


INSERT INTO services (ID, NAME,DESCRIPTION, PRICE) VALUES (1, 'Coiffures','Coiffures', 10);
INSERT INTO services (ID, NAME,DESCRIPTION, PRICE) VALUES (2, 'maquillages','maquillages', 20);
INSERT INTO services (ID, NAME,DESCRIPTION, PRICE) VALUES (3, 'soins visage et corps','soins visage et corps', 15);
INSERT INTO services (ID, NAME,DESCRIPTION, PRICE) VALUES (4, 'beauté des mains et des pieds','beauté des mains et des pieds', 30);


INSERT INTO ESTHETICIANS_SERVICES (SERVICE_ID,ESTHESTICIAN_ID) VALUES (1,1);
INSERT INTO ESTHETICIANS_SERVICES (SERVICE_ID,ESTHESTICIAN_ID) VALUES (2,1);
INSERT INTO ESTHETICIANS_SERVICES (SERVICE_ID,ESTHESTICIAN_ID) VALUES (3,2);
INSERT INTO ESTHETICIANS_SERVICES (SERVICE_ID,ESTHESTICIAN_ID) VALUES (4,2);
